### ISSUE TITLE
[PE-D] Commands that need a group name require typing the exact group name to be valid

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W16-3/tp#149]
Example command:
![image.png](https://raw.githubusercontent.com/jaysmyname/ped/main/files/4b1b74fd-0e51-473e-bae9-888598aa7829.png)

This is not optimised for users to be productive or efficient, as they would need to check the exact group names and type it exactly, wasting time.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: jaysmyname/ped#8

**Comment by Punpun1643** [comment]
I agree that this may be considered as `type.FeatureFlaw` but definitely not `severity.High`. I would consider it as `severity.Low`, given especially that it is for **fast typist** who would not really find this as a huge problem. 

Moreover, as a user, if I were to want to delete a group, I would already **know** which group I would want to delete and hence **what is the group name**. The app is already designed such that the user would not have to type the **exact group name with case sensitivity**. They can just type anything as long as the spacing is correct. I don't see this as a problem if the user already know the group name that they want to delete.
