### ISSUE TITLE
[PE-D] `add` command throws wrong error message when given incorrect command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W16-3/tp#156]
![Screenshot 2022-04-01 at 2.59.18 PM.png](https://raw.githubusercontent.com/aceszhenwei/ped/main/files/35e60ede-f338-4bcc-ba7e-7c34c1d7047f.png)

The error message states that the student already exists in Archduke. However, the command given is incorrect and should throw in an incorrect format error instead.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: aceszhenwei/ped#8

**Comment by Punpun1643** [comment]
Please refer to [the explanation on this issue](https://github.com/AY2122S2-CS2103-W16-3/tp/issues/165#issuecomment-1086877580).
